<a href="https://colab.research.google.com/github/Pranav123-AP/Python-with-Machine-Learning/blob/main/numpy3_077.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
#filter
arr=np.array([41,42,43,44])
filter_arr= arr>42
x=[True,False,True,False]
newarr=arr[filter_arr]
print("\nOriginal array:",arr)
print("\nFilter array:condition->42:", filter_arr)
print("\nNew array:",newarr)


Original array: [41 42 43 44]

Filter array:condition->42: [False False  True  True]

New array: [43 44]


In [14]:
#filter
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("n\Filter array:",newarr)


Original array: [41 42 43 44]

Filter index: [True, False, True, False]
n\Filter array: [41 43]


<>:7: SyntaxWarning: invalid escape sequence '\F'
<>:7: SyntaxWarning: invalid escape sequence '\F'
/tmp/ipython-input-1524749776.py:7: SyntaxWarning: invalid escape sequence '\F'
  print("n\Filter array:",newarr)


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,4,6,4])
print(arr)
x=np.where(arr==4)
print(x)

[1 2 3 4 5 4 6 4]
(array([3, 5, 7]),)


In [10]:
#indexes where the values are even
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(arr)
print(x)

[1 2 3 4 5 6 7 8]
(array([1, 3, 5, 7]),)


In [11]:
#sorting the array
arr=np.array([3,2,0,1])
print("\nOriginal array:",arr)
print("\nSorted array:",np.sort(arr))
arr=np.array([[3,2,4],[5,0,1]])
print("\nOriginal array:\n",arr)
print("\nSorted array:\n",np.sort(arr))



Original array: [3 2 0 1]

Sorted array: [0 1 2 3]

Original array:
 [[3 2 4]
 [5 0 1]]

Sorted array:
 [[2 3 4]
 [0 1 5]]


In [13]:
import numpy as np
sorted_array=np.array([1,3,5,7])
values=[2,4,6]
insert_indices=np.searchsorted(sorted_array,values)
print(sorted_array)
print(values)
print(insert_indices)

[1 3 5 7]
[2, 4, 6]
[1 2 3]
