<a href="https://colab.research.google.com/github/Pranav123-AP/Python-with-Machine-Learning/blob/main/numpy4_077.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Program
import numpy as np
arr1=[10,20,30,40]
arr2=[2,4,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("Original arrays")
print(a)
print(b)
print("\nVector addition")
print(a+b)
print("\nVector subtraction")
print(a-b)
print("\nVector multiplication")
print(a*b)
print("\nVector division")
print(a/b)
print("\nVector Dot product")
print(a.dot(b))
print("\nScalar multiplication")
sclr=5
print("scalar value=",sclr)
print("array=",a)
print("result=",a*sclr)
#Numpy.Vectorize method
def my_func(x,y):
  #Return x-y if x>y, otherwise return x+y
  if x>y:
    return x-y
  else:
    return x+y
print("\n\nNumpy.Vectorize method")
print("(Return x-y if x>y.otherwise return x+y)")
arr1=[10,4,20]
arr2=[2,3,30]
vec_func=np.vectorize(my_func)
print("array1:",arr1)
print("array2:",arr2)
print("result:",vec_func(arr1,arr2))

Original arrays
[10 20 30 40]
[ 2  4  8 10]

Vector addition
[12 24 38 50]

Vector subtraction
[ 8 16 22 30]

Vector multiplication
[ 20  80 240 400]

Vector division
[5.   5.   3.75 4.  ]

Vector Dot product
740

Scalar multiplication
scalar value= 5
array= [10 20 30 40]
result= [ 50 100 150 200]


Numpy.Vectorize method
(Return x-y if x>y.otherwise return x+y)
array1: [10, 4, 20]
array2: [2, 3, 30]
result: [ 8  1 50]
