<a href="https://colab.research.google.com/github/Pranav123-AP/Python-with-Machine-Learning/blob/main/numpy1_077.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a= np.array([[1,2,3],[5,8,7]])
print("Array Created: \n",a)

Array Created: 
 [[1 2 3]
 [5 8 7]]


In [ ]:
#creating a 3X4 array with all zeros
b= np.zeros((4,3))
print("Array with all zeros:\n",b)

Array with all zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#creat a constant Value array
c=np.full((3,3),6)
print("Array with all 6s:\n",c)

Array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
#creating an array with random value
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.23544295 0.5702153 ]
 [0.43971337 0.58155933]]


In [8]:
#create a sequence of integers from 0 to 30 with step of 5
import numpy as np
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [9]:
#reshaping 3X4 array in 2X3X3 array
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\n original array:\n",arr)
print("Reshaped array[4,3]:\n",arr)



 original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]


In [10]:
#flatten array
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
flarr=arr.flatten()
print("\n Flattened array:\n",flarr)
print("\n Flattened array:\n",flarr)


 Flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]

 Flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [14]:
#import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
print("\n no of dimensions:\n",arr.ndim)
print("\n shape of array:\n",arr.shape)
print("\n size of array:\n",arr.size)
print("\n array type:\n",arr.dtype)
newtype=arr.astype('f')
print("\n converted array element:\n",arr.size)
print("\n converted array type:\n",newtype.dtype)


 no of dimensions:
 2

 shape of array:
 (3, 4)

 size of array:
 12

 array type:
 int64

 converted array element:
 12

 converted array type:
 float32


In [15]:
#slicing
import numpy as np
p= np.array ([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])
print(p[2:0:2])
print(p[3:,3:])
print(p[2:2:])
print(p[:,1])
c=p.astype('f')
print(c)
e=p.astype('f')
print(e)

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[]
[]
[]
[ 2  5  8 11 14]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
